set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(triple arm-linux-gnueabihf)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-shift-count-overflow -Wno-format-overflow -Wno-int-to-pointer-cast -Wno-error=pointer-to-int-cast")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-shift-count-overflow -Wno-error=narrowing")

set(IREE_HAL_DRIVER_DEFAULTS OFF)
set(IREE_HAL_DRIVER_LOCAL_SYNC ON)

set(IREE_BUILD_TESTS OFF)
# This fails because simple_embedding_test_bytecode_module_cpu_arm_32_c.h is
# missing but i think that it is somehow supposed to be generated by
# simple_embedding_test.mlir
set(IREE_BUILD_SAMPLES OFF)
